# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      covid19-db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ROOT
          MYSQL_DATABASE: covid19
          MYSQL_USER: covid19
          MYSQL_PASSWORD: COVID19
          TZ: 'Asia/Tokyo'
        options:
          -v /docker/mysql/data:/var/lib/mysql
          -v /docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
          -v /docker/mysql/initdb:/docker-entrypoint-initdb.d
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
